version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: cm_user
      POSTGRES_PASSWORD: CmUser@123
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fastapi_api
    restart: always
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL_SYNC: postgresql://cm_user:CmUser%40123@db:5432/marketplace_db
      DATABASE_URL_ASYNC: postgresql+asyncpg://cm_user:CmUser%40123@db:5432/marketplace_db
      SECRET_KEY: supersecretkey
      STRIPE_SECRET_KEY: sk_test_xxx
      STRIPE_WEBHOOK_SECRET: whsec_xxx


volumes:
  postgres_data:
